# Form implementation generated from reading ui file '.\chart.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DlgChart(object):
    def setupUi(self, DlgChart):
        DlgChart.setObjectName("DlgChart")
        DlgChart.resize(400, 300)
        self.mainLayout = QtWidgets.QHBoxLayout(DlgChart)
        self.mainLayout.setObjectName("mainLayout")

        self.retranslateUi(DlgChart)
        QtCore.QMetaObject.connectSlotsByName(DlgChart)

    def retranslateUi(self, DlgChart):
        _translate = QtCore.QCoreApplication.translate
        DlgChart.setWindowTitle(_translate("DlgChart", "Form"))
