# Form implementation generated from reading ui file '.\radius_to_cut.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DlgRadiusToCutWindow(object):
    def setupUi(self, DlgRadiusToCutWindow):
        DlgRadiusToCutWindow.setObjectName("DlgRadiusToCutWindow")
        DlgRadiusToCutWindow.resize(386, 176)
        self.verticalLayout = QtWidgets.QVBoxLayout(DlgRadiusToCutWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.msgLabel = QtWidgets.QLabel(parent=DlgRadiusToCutWindow)
        self.msgLabel.setObjectName("msgLabel")
        self.horizontalLayout.addWidget(self.msgLabel)
        self.radiusSpinBox = QtWidgets.QSpinBox(parent=DlgRadiusToCutWindow)
        self.radiusSpinBox.setObjectName("radiusSpinBox")
        self.horizontalLayout.addWidget(self.radiusSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.submitBtn = QtWidgets.QPushButton(parent=DlgRadiusToCutWindow)
        self.submitBtn.setObjectName("submitBtn")
        self.horizontalLayout_2.addWidget(self.submitBtn)
        self.cancelBtn = QtWidgets.QPushButton(parent=DlgRadiusToCutWindow)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout_2.addWidget(self.cancelBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(DlgRadiusToCutWindow)
        self.submitBtn.clicked.connect(DlgRadiusToCutWindow.accept) # type: ignore
        self.cancelBtn.clicked.connect(DlgRadiusToCutWindow.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DlgRadiusToCutWindow)

    def retranslateUi(self, DlgRadiusToCutWindow):
        _translate = QtCore.QCoreApplication.translate
        DlgRadiusToCutWindow.setWindowTitle(_translate("DlgRadiusToCutWindow", "Dialog"))
        self.msgLabel.setText(_translate("DlgRadiusToCutWindow", "TextLabel"))
        self.submitBtn.setText(_translate("DlgRadiusToCutWindow", "OK"))
        self.cancelBtn.setText(_translate("DlgRadiusToCutWindow", "Отмена"))
