# Form implementation generated from reading ui file '.\stats.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DlgStats(object):
    def setupUi(self, DlgStats):
        DlgStats.setObjectName("DlgStats")
        DlgStats.resize(551, 524)
        DlgStats.setModal(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DlgStats)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.polymersListWidget = QtWidgets.QListWidget(parent=DlgStats)
        self.polymersListWidget.setObjectName("polymersListWidget")
        self.horizontalLayout.addWidget(self.polymersListWidget)
        self.stats_layout = QtWidgets.QFormLayout()
        self.stats_layout.setObjectName("stats_layout")
        self.horizontalLayout.addLayout(self.stats_layout)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=DlgStats)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(DlgStats)
        self.buttonBox.accepted.connect(DlgStats.accept) # type: ignore
        self.buttonBox.rejected.connect(DlgStats.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DlgStats)

    def retranslateUi(self, DlgStats):
        _translate = QtCore.QCoreApplication.translate
        DlgStats.setWindowTitle(_translate("DlgStats", "Статистика для глобулы"))
