# Form implementation generated from reading ui file '.\uis\start_settings_window.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_StartSettingsWindow(object):
    def setupUi(self, StartSettingsWindow):
        StartSettingsWindow.setObjectName("StartSettingsWindow")
        StartSettingsWindow.resize(252, 112)
        self.verticalLayout = QtWidgets.QVBoxLayout(StartSettingsWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=StartSettingsWindow)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spaceDimentionSpinBox = QtWidgets.QSpinBox(parent=StartSettingsWindow)
        self.spaceDimentionSpinBox.setMinimum(2)
        self.spaceDimentionSpinBox.setMaximum(100)
        self.spaceDimentionSpinBox.setProperty("value", 2)
        self.spaceDimentionSpinBox.setObjectName("spaceDimentionSpinBox")
        self.horizontalLayout.addWidget(self.spaceDimentionSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=StartSettingsWindow)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(StartSettingsWindow)
        self.buttonBox.accepted.connect(StartSettingsWindow.accept) # type: ignore
        self.buttonBox.rejected.connect(StartSettingsWindow.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(StartSettingsWindow)

    def retranslateUi(self, StartSettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        StartSettingsWindow.setWindowTitle(_translate("StartSettingsWindow", "Dialog"))
        self.label.setText(_translate("StartSettingsWindow", "Введите размерность пространства"))
