# Form implementation generated from reading ui file '.\stats.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DlgStats(object):
    def setupUi(self, DlgStats):
        DlgStats.setObjectName("DlgStats")
        DlgStats.resize(551, 524)
        DlgStats.setModal(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DlgStats)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=DlgStats)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.massCenterLabel = QtWidgets.QLabel(parent=DlgStats)
        self.massCenterLabel.setObjectName("massCenterLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.massCenterLabel)
        self.label_2 = QtWidgets.QLabel(parent=DlgStats)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.dispersityLabel = QtWidgets.QLabel(parent=DlgStats)
        self.dispersityLabel.setObjectName("dispersityLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dispersityLabel)
        self.label_4 = QtWidgets.QLabel(parent=DlgStats)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.stdDeviationLabel = QtWidgets.QLabel(parent=DlgStats)
        self.stdDeviationLabel.setObjectName("stdDeviationLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.stdDeviationLabel)
        self.label_6 = QtWidgets.QLabel(parent=DlgStats)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6)
        self.meanValueLabel = QtWidgets.QLabel(parent=DlgStats)
        self.meanValueLabel.setObjectName("meanValueLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.meanValueLabel)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.chartLayout = QtWidgets.QVBoxLayout()
        self.chartLayout.setObjectName("chartLayout")
        self.horizontalLayout_2.addLayout(self.chartLayout)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.polymersListWidget = QtWidgets.QListWidget(parent=DlgStats)
        self.polymersListWidget.setObjectName("polymersListWidget")
        self.horizontalLayout_3.addWidget(self.polymersListWidget)
        self.stats_layout = QtWidgets.QFormLayout()
        self.stats_layout.setObjectName("stats_layout")
        self.horizontalLayout_3.addLayout(self.stats_layout)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=DlgStats)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(DlgStats)
        self.buttonBox.accepted.connect(DlgStats.accept) # type: ignore
        self.buttonBox.rejected.connect(DlgStats.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DlgStats)

    def retranslateUi(self, DlgStats):
        _translate = QtCore.QCoreApplication.translate
        DlgStats.setWindowTitle(_translate("DlgStats", "Статистика для глобулы"))
        self.label.setText(_translate("DlgStats", "Центр масс"))
        self.massCenterLabel.setText(_translate("DlgStats", "TextLabel"))
        self.label_2.setText(_translate("DlgStats", "Дисперсия"))
        self.dispersityLabel.setText(_translate("DlgStats", "TextLabel"))
        self.label_4.setText(_translate("DlgStats", "Стандартное отклонение"))
        self.stdDeviationLabel.setText(_translate("DlgStats", "TextLabel"))
        self.label_6.setText(_translate("DlgStats", "Мат. ожидание"))
        self.meanValueLabel.setText(_translate("DlgStats", "TextLabel"))
